(()=>{const c=document.getElementById('game'),x=c.getContext('2d');let w,h;function size(){w=innerWidth;h=innerHeight;c.width=w*devicePixelRatio;c.height=h*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',size);size();
const zones=[['🧩','Gerbang Algoritma',240,240],['🖥️','Kota Sistem Komputer',800,270],['🌐','Jalur Jaringan',1380,300],['🔐','Benteng Keamanan',1900,520],['📊','Laboratorium Data',1650,1080],['🧠','Ruang CPU',1050,1250],['⚙️','Bengkel Sistem Operasi',500,1200],['🔎','Menara Pencarian',230,820],['🏆','Pusat Misi',1050,760]];
const npcs=zones.map((z,i)=>({x:z[2],y:z[3],i}));let p={x:120,y:240,r:18,s:4};let keys={},cam={x:0,y:0};let S=JSON.parse(localStorage.getItem('KISMA3')||'null')||{xp:0,life:3,key:0,done:[],name:'',cls:''};const W=2300,H=1700;
addEventListener('keydown',e=>{keys[e.key]=1;if(e.key.toLowerCase()=='e')interact()});addEventListener('keyup',e=>keys[e.key]=0);document.querySelectorAll('[data-k]').forEach(b=>{b.onpointerdown=()=>keys[b.dataset.k]=1;b.onpointerup=()=>keys[b.dataset.k]=0});document.getElementById('use').onclick=interact;
function save(){localStorage.setItem('KISMA3',JSON.stringify(S));document.getElementById('xp').textContent=S.xp;document.getElementById('life').textContent=S.life;document.getElementById('key').textContent=S.key;document.getElementById('quest').textContent=S.done.length<9?'Misi '+(S.done.length+1)+'/9: '+zones[S.done.length][1]:'🎉 Semua misi selesai!'}
function start(){S.name=document.getElementById('name').value||'Petualang';S.cls=document.getElementById('cls').value||'X';document.getElementById('modal').style.display='none';save();say('Wali Kota Digital',['Selamat datang, '+S.name+'!','Ikuti jalan kota dan temui NPC di setiap wilayah.','Selesaikan misi berurutan untuk membuka rute berikutnya.'])}
document.getElementById('start').onclick=start;document.getElementById('reset').onclick=()=>{if(confirm('Hapus progres?')){localStorage.removeItem('KISMA3');location.reload()}};document.getElementById('help').onclick=()=>say('Cara Bermain',['WASD / tombol panah = bergerak.','E / INTERAKSI = berbicara dan memulai misi.','Selesaikan misi untuk mendapat XP dan kunci.','Area terkunci sampai misi sebelumnya selesai.']);
function say(title,lines){let m=document.getElementById('panel');m.innerHTML='<section><h2>'+title+'</h2>'+lines.map(t=>'<p style="text-align:left;color:#dbe8f5;font-weight:400;letter-spacing:0">'+t+'</p>').join('')+'<button class="primary" id="close">LANJUT</button></section>';m.style.display='flex';document.getElementById('close').onclick=()=>m.style.display='none'}
function interact(){let n=npcs.find(n=>Math.hypot(p.x-n.x,p.y-n.y)<75);if(!n)return;let i=n.i;if(S.done.includes(i))return say(zones[i][1],['Misi ini sudah selesai. Jelajahi kota untuk menemukan area berikutnya.']);if(i>0&&!S.done.includes(i-1))return say('Gerbang terkunci',['🔒 Selesaikan misi sebelumnya untuk membuka wilayah ini.']);mission(i)}
function finish(i,pts=100){if(!S.done.includes(i))S.done.push(i);S.xp+=pts;S.key++;save();document.getElementById('panel').style.display='none';say('Misi Berhasil!',['✅ '+zones[i][1]+' selesai!','⭐ +'+pts+' XP','🔑 Kamu mendapatkan satu kunci wilayah.']);}
function fail(){S.life--;if(S.life<=0)S.life=3;save()}
function mission(i){let m=document.getElementById('panel');m.style.display='flex';let body='';if(i==0){body='<h2>🧩 Algoritma</h2><p style="text-align:left">Susun langkah berikut dari awal sampai akhir.</p><div class="seq" id="seq"></div><p id="ans" style="text-align:left;color:#fff;letter-spacing:0"></p>';m.innerHTML='<section>'+body+'</section>';let a=['Masukkan bahan','Proses','Periksa hasil','Sajikan'],picked=[];a.sort(()=>Math.random()-.5).forEach(t=>{let b=document.createElement('button');b.className='chip';b.textContent=t;b.onclick=()=>{if(!picked.includes(t)){picked.push(t);b.classList.add('on');document.getElementById('ans').textContent=picked.join(' → ');if(picked.length==4){if(picked.join('|')=='Masukkan bahan|Proses|Periksa hasil|Sajikan')finish(i);else{fail();picked=[];document.querySelectorAll('.chip').forEach(z=>z.classList.remove('on'));document.getElementById('ans').textContent='Coba lagi.'}}}};document.getElementById('seq').appendChild(b)});
}else{let qs=[['🖥️ Sistem Komputer','Alur IPO yang benar adalah…',['Keyboard → Proses → Monitor','Monitor → Keyboard → CPU','CPU → Keyboard → Monitor'],0],['🌐 Jaringan','Urutan PC menuju server yang benar…',['PC → Switch → Router → Internet → Server','Server → PC → Router → Switch','PC → Server → Keyboard'],0],['🔐 Keamanan','Pesan meminta password melalui tautan mencurigakan. Tindakan aman?',['Klik dan kirim password','Periksa pengirim dan verifikasi lewat kanal resmi','Teruskan ke semua teman'],1],['📊 Data','Total penjualan: Roti 90, Teh 135, Susu 90. Tertinggi?',['Roti','Teh','Susu'],1],['🧠 CPU','Urutan siklus instruksi CPU yang benar?',['Execute → Decode → Fetch','Fetch → Decode → Execute','Decode → Fetch → Execute'],1],['⚙️ OS','Banyak aplikasi membuat komputer lambat. OS sebaiknya…',['Mengelola proses dan memori','Menghapus monitor','Mengganti wallpaper'],0],['🔎 Pencarian','Cara mengecek validitas sumber paling kuat?',['Percaya karena viral','Cek penulis, tanggal, bukti dan bandingkan sumber','Pilih gambar terbaik'],1],['🏆 Final','Server festival bermasalah karena rute dan login. Langkah logis?',['Perbaiki jaringan, amankan autentikasi, lalu uji','Bagikan password admin','Hapus semua data'],0]][i];m.innerHTML='<section><h2>'+qs[0]+' '+qs[1]+'</h2><div class="grid" id="opts"></div></section>';qs[2].forEach((t,j)=>{let b=document.createElement('button');b.className='opt';b.textContent=t;b.onclick=()=>{if(j==qs[3]){b.classList.add('ok');setTimeout(()=>finish(i,100+i*5),250)}else{b.classList.add('bad');fail()}};document.getElementById('opts').appendChild(b)})}}
function draw(){x.fillStyle='#0b3b30';x.fillRect(0,0,w,h);cam.x=Math.max(0,Math.min(W-w,p.x-w/2));cam.y=Math.max(0,Math.min(H-h,p.y-h/2));x.save();x.translate(-cam.x,-cam.y);x.fillStyle='#173f34';x.fillRect(0,0,W,H);x.strokeStyle='#243b52';x.lineWidth=95;x.lineCap='round';[[[120,240],[800,270],[1380,300],[1900,520]],[[1900,520],[1650,1080],[1050,1250],[500,1200],[230,820],[240,240]],[[1050,760],[1050,1250]]].forEach(r=>{x.beginPath();r.forEach((p,j)=>j?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.stroke()});x.strokeStyle='#547087';x.lineWidth=70;[[[120,240],[800,270],[1380,300],[1900,520]],[[1900,520],[1650,1080],[1050,1250],[500,1200],[230,820],[240,240]],[[1050,760],[1050,1250]]].forEach(r=>{x.beginPath();r.forEach((p,j)=>j?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.stroke()});zones.forEach((z,i)=>{let ok=i==0||S.done.includes(i-1);x.fillStyle=ok?'#17304a':'#25303b';x.fillRect(z[2]-65,z[3]-45,130,90);x.font='26px serif';x.textAlign='center';x.fillText(ok?z[0]:'🔒',z[2],z[3]);x.font='bold 12px system-ui';x.fillStyle='#fff';x.fillText(z[1],z[2],z[3]+58)});npcs.forEach(n=>{let ok=n.i==0||S.done.includes(n.i-1);x.globalAlpha=ok?1:.35;x.font='28px serif';x.fillText('🧑‍💻',n.x,n.y+8);x.globalAlpha=1});x.fillStyle='#ffd166';x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill();x.fillStyle='#2b3c5a';x.fillRect(p.x-10,p.y+5,20,15);x.restore();requestAnimationFrame(draw)}
save();draw()})();
